name: Deploy Miranda Web Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull from GitHub repository and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            sudo su || exit
            cd /var/www/Miranda-Laravel || exit
            git pull origin main || exit
            composer install || exit
            php artisan migrate || exit
            sudo systemctl restart apache2 || exit
          EOF
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Check if server is up
        run: |
          curl -f http://$EC2_HOST || exit 1
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}